myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from scriptly.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home.home, name='scriptly_home'),
    path('group/<int:group_id>/', home.script_group_detail, name='script_group_detail'),
    path('scripts/', include(('scriptly.urls', 'scriptly'), namespace='scriptly')),  # ✅ Now Django knows 'scriptly' is a namespace

]

scriptly/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from scriptly.views import celery_results_view
from .views import celery_results_view
from scriptly.views.views import ScriptlyScriptSubmitView


from scriptly.views import (
    ScriptlyHomeView,
    ScriptlyScriptView,
    ScriptlyScriptSearchJSON,
    ScriptlyScriptSearchJSONHTML,
    UserResultsView,
    user_results_json,
    ScriptlyProfileView,
    scriptly_login,
    ScriptlyRegister,
    toggle_favorite,
)
from scriptly.views.home import home, script_group_detail

app_name = "scriptly"

urlpatterns = [
    path('', ScriptlyHomeView.as_view(), name='scriptly_home'),
    path('scripts/submit/', ScriptlyScriptSubmitView.as_view(), name='scriptly_submit_script'),
    path('jobs/results/<int:job_id>/', celery_results_view, name='celery_results'),
    # Script detail and execution
    path('scripts/<slug:slug>/', ScriptlyScriptView.as_view(), name='scriptly_script'),
    path('scripts/jobs/results/celery_results/<int:job_id>/', celery_results_view, name='celery_results'),
    path('scripts/jobs/results/status/<int:job_id>/', celery_results_view, name='job_status'),
    # Script search endpoints
    path("scripts/search/script/json", ScriptlyScriptSearchJSON.as_view(), name="scriptly_search_script_json"),
    path('scripts/search/jsonhtml', ScriptlyScriptSearchJSONHTML.as_view(), name='scriptly_search_script_jsonhtml'),


    # User results
    path('scripts/jobs/results/user', UserResultsView.as_view(), name='user_results'),
    path('scripts/jobs/results/user/json', user_results_json, name='user_results_json'),

    # Profile
    path('profile/', ScriptlyProfileView.as_view(), name='profile_home'),
    path('profile/<str:username>/', ScriptlyProfileView.as_view(), name='profile'),

    # Groups
    path('group/<int:group_id>/', login_required(script_group_detail), name='script_group_detail'),

    # Auth
    path('accounts/register/', ScriptlyRegister.as_view(), name='scriptly_register'),
    path('admin/login/', scriptly_login, name='scriptly_login'),

    # Favorites
    path('favorite/toggle', toggle_favorite, name='toggle_favorite'),

    # Internationalization
    path('i18n/', include('django.conf.urls.i18n')),
]

scriptly/api/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class SubmitForm(forms.Form):
    job_name = forms.CharField()
    job_description = forms.CharField(required=False)
    version = forms.CharField(required=False)
    iteration = forms.IntegerField(required=False)
    command = forms.CharField(required=False)


class AddScriptForm(forms.Form):
    group = forms.CharField(required=False)
    default = forms.NullBooleanField(required=False)
    ignore_bad_imports = forms.BooleanField(
        required=False,
        help_text=_(
            "Ignore bad imports when adding scripts. This is useful if a script is under a virtual environment."
        ),
    )

    def clean_default(self):
        if self.cleaned_data["default"] is None:
            return True
        return self.cleaned_data["default"]

    def clean_ignore_bad_imports(self):
        if self.cleaned_data["ignore_bad_imports"] is None:
            return False
        return self.cleaned_data["ignore_bad_imports"]

scriptly/forms/config.py
SCRIPTLY_MULTI_WIDGET_ATTR = "data-scriptly-multiple"
SCRIPTLY_MULTI_WIDGET_ANCHOR = "scriptly-multi-input"

scriptly/forms/fields.py
from __future__ import absolute_import

__author__ = "chris"
from django.forms import FileField
from django.forms import widgets


class ScriptlyOutputFileField(FileField):
    widget = widgets.TextInput

    def __init__(self, *args, **kwargs):
        kwargs["allow_empty_file"] = True
        super(ScriptlyOutputFileField, self).__init__(*args, **kwargs)


# TODO: Make a complex widget of filepathfield/filefield
class ScriptlyUploadFileField(FileField):
    pass

scriptly/forms/profile.py
from django import forms


class APIKeyForm(forms.Form):
    name = forms.CharField()

scriptly/forms/scripts.py
from __future__ import absolute_import
from django import forms


class ScriptlyForm(forms.Form):
    scriptly_type = forms.IntegerField(widget=forms.HiddenInput)
    scriptly_parser = forms.IntegerField(widget=forms.HiddenInput, required=False)

    def add_scriptly_fields(self):
        # This adds fields such as job name, description that we like to validate on but don't want to include in
        # form rendering
        self.fields["job_name"] = forms.CharField()
        self.fields["job_description"] = forms.CharField(required=False)

scriptly/views/authentication.py
from __future__ import absolute_import
from django.contrib.auth import login, authenticate, get_user_model
from django.forms.models import modelform_factory
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import force_str
from django.views.generic import CreateView

from .. import settings as scriptly_settings


class ScriptlyRegister(CreateView):
    template_name = "scriptly/registration/register.html"
    model = get_user_model()
    fields = ("username", "email", "password")

    def dispatch(self, request, *args, **kwargs):
        if not scriptly_settings.SCRIPTLY_AUTH:
            return HttpResponseRedirect(scriptly_settings.SCRIPTLY_REGISTER_URL)
        return super(ScriptlyRegister, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form_class()
        post = request.POST.copy()
        post["username"] = post["username"].lower()
        form = form(post)
        if request.POST["password"] != request.POST["password2"]:
            form.add_error("password", _("Passwords do not match."))
        if request.POST["username"].lower() == "admin":
            form.add_error("username", _("Reserved username."))
        if not request.POST["email"]:
            form.add_error("email", _("Please enter your email address."))
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        next_url = self.request.POST.get("next")
        # for some bizarre reason the password isn't setting by the modelform
        self.object.set_password(self.request.POST["password"])
        self.object.save()
        auser = authenticate(
            username=self.object.username, password=self.request.POST["password"]
        )
        login(self.request, auser)
        return reverse(next_url) if next_url else reverse("scriptly:scriptly_home")


def scriptly_login(request):
    if not scriptly_settings.SCRIPTLY_AUTH:
        return HttpResponseRedirect(scriptly_settings.SCRIPTLY_LOGIN_URL)
    User = get_user_model()
    form = modelform_factory(User, fields=("username", "password"))
    user = User.objects.filter(username=request.POST.get("username"))
    if user:
        user = user[0]
    else:
        user = None
    form = form(request.POST, instance=user)
    if form.is_valid():
        data = form.cleaned_data
        user = authenticate(username=data["username"], password=data["password"])
        if user is None:
            return JsonResponse(
                {
                    "valid": False,
                    "errors": {
                        "__all__": [
                            force_str(
                                _("You have entered an invalid username or password.")
                            )
                        ]
                    },
                }
            )
        login(request, user)
        return JsonResponse({"valid": True, "redirect": request.POST["next"]})
    else:
        return JsonResponse({"valid": False, "errors": form.errors})

scriptly/views/favorite.py
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.http import (
    HttpResponseForbidden,
    HttpResponseNotFound,
    HttpResponseBadRequest,
    JsonResponse,
)
from django.views.decorators.csrf import ensure_csrf_cookie

from ..models import Favorite


@login_required
@ensure_csrf_cookie
def toggle_favorite(request):
    """
    Add/remove an object to the user's favorites. Checks for existence and adds if not, else removes.
    This is the underlying mechanism for adding items to the user 'scrapbook' and favorite scripts.

    :param request:
    :param file_id:
    :return:
    """
    if not request.is_ajax():
        return HttpResponseForbidden()

    try:
        app, model, pk = (
            request.POST["app"],
            request.POST["model"],
            int(request.POST["pk"]),
        )

    except ValueError:
        return HttpResponseBadRequest()

    try:
        ctype = ContentType.objects.get(app_label=app, model=model)
        obj = ctype.get_object_for_this_type(id=pk)

    except Favorite.DoesNotExist:
        return HttpResponseNotFound()

    try:
        fave = Favorite.objects.get(
            content_type=ctype, object_id=obj.id, user=request.user
        )

    except Favorite.DoesNotExist:
        # Does not exist, so create it
        fave = Favorite(content_object=obj, user=request.user)
        fave.save()
        is_favorite = True

    else:
        # Exists, so delete it
        fave.delete()
        is_favorite = False

    # Return the current total number for UI updates
    favorites_count = Favorite.objects.filter(
        content_type=ctype, user=request.user
    ).count()

    return JsonResponse(
        {
            "app": app,
            "model": model,
            "pk": pk,
            "is_favorite": is_favorite,
            "count": favorites_count,
        }
    )

scriptly/views/home.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from scriptly.models import Script, ScriptGroup, ScriptVersion
from scriptly.backend import utils
from django.urls import reverse

@csrf_exempt
@login_required
def script_group_detail(request, group_id):
    if request.method == "POST":
        post = request.POST.copy()
        user = request.user if request.user.is_authenticated else None

        form = utils.get_master_form(
            pk=int(post.get("scriptly_type")),
            parser=int(post.get("scriptly_parser", 0))
        )

        utils.validate_form(form=form, data=post, files=request.FILES)

        if not form.errors:
            version_pk = form.cleaned_data.get("scriptly_type")
            parser_pk = form.cleaned_data.get("scriptly_parser")

            try:
                script_version = ScriptVersion.objects.get(pk=version_pk)
            except ScriptVersion.DoesNotExist:
                return JsonResponse({"valid": False, "errors": {"__all__": ["Script version not found."]}})

            valid = utils.valid_user(script_version.script, request.user).get("valid")
            group_valid = utils.valid_user(script_version.script.script_group, request.user).get("valid")

            if valid and group_valid:
                job = utils.create_scriptly_job(
                    script_parser_pk=parser_pk,
                    script_version_pk=version_pk,
                    user=user,
                    data=form.cleaned_data,
                )
                job.execute_sync()

                return JsonResponse({
                    "valid": True,
                    "job_id": job.id,
                    "redirect": reverse("scriptly:celery_results", kwargs={"job_id": job.id}),
                    "message": "Job completed successfully",
                })

        return JsonResponse({"valid": False, "errors": form.errors})

    # GET handler stays unchanged
    group = get_object_or_404(ScriptGroup, pk=group_id)
    scripts = Script.objects.filter(script_group=group, is_active=True)
    script_data = []

    for script in scripts:
        try:
            default_version = ScriptVersion.objects.get(script=script, default_version=True)
            form_groups = utils.get_form_groups(script_version=default_version)
            script_data.append({
                "id": script.id,
                "slug": script.slug,
                "script_name": script.script_name,
                "script_description": script.script_description,
                "modified_date": default_version.modified_date,
                "created_by": default_version.created_by,
                "form_action_url": reverse("scriptly:script_group_detail", kwargs={"group_id": group.id}),
                "parsers": form_groups["parsers"],
                "scriptly_form": form_groups["scriptly_form"],
            })
        except ScriptVersion.DoesNotExist:
            continue

    return render(request, "scriptly/script_group_detail.html", {
        "group": group,
        "scripts": script_data,
    })


@login_required
def home(request):
    groups = ScriptGroup.objects.prefetch_related('script_set').all()
    for group in groups:
        scripts = Script.objects.filter(script_group=group, is_active=True)
        enriched_scripts = []
        for script in scripts:
            try:
                version = ScriptVersion.objects.get(script=script, default_version=True)
            except ScriptVersion.DoesNotExist:
                version = None
            enriched_scripts.append({
                'script_name': script.script_name,
                'slug': script.slug,
                'script_description': script.script_description or "No description.",
                'modified_date': version.modified_date if version else None,
                'created_by': version.created_by.username if version and version.created_by else "Unknown",
            })
        group.scripts = enriched_scripts

    return render(request, 'scriptly/home.html', {'groups': groups})

scriptly/views/profile.py
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods

from ..forms import APIKeyForm
from ..models import APIKey, ScriptlyProfile
from ..utils import requires_login


@require_http_methods(["POST"])
@requires_login
def toggle_api_key(request, id):
    user = request.user
    profile, _ = ScriptlyProfile.objects.get_or_create(user=user)
    try:
        api_key = APIKey.objects.get(pk=id, profile=profile)
    except APIKey.DoesNotExist:
        return HttpResponse("API Key not found", status=404)
    api_key.active = not api_key.active
    api_key.save()
    return JsonResponse(
        {
            "id": api_key.id,
            "active": api_key.active,
        }
    )


@require_http_methods(["POST"])
@requires_login
def create_api_key(request):
    user = request.user
    profile, _ = ScriptlyProfile.objects.get_or_create(user=user)
    form = APIKeyForm(request.POST)
    if form.is_valid():
        api_key = APIKey(
            name=form.cleaned_data["name"],
            profile=profile,
        )
        api_key.save()

        return JsonResponse(
            {
                "id": api_key.id,
                "name": api_key.name,
                "created_date": api_key.created_date,
                "api_key": api_key._api_key,
            }
        )
    else:
        return JsonResponse({"valid": False, "errors": form.errors})


@require_http_methods(["DELETE"])
@requires_login
def delete_api_key(request, id):
    user = request.user
    profile, _ = ScriptlyProfile.objects.get_or_create(user=user)
    try:
        api_key = APIKey.objects.get(pk=id, profile=profile)
    except APIKey.DoesNotExist:
        return HttpResponse("API Key not found", status=404)
    api_key.delete()
    return JsonResponse(
        {
            "id": api_key.id,
        }
    )

scriptly/views/search.py
# scriptly/views/search.py
from django.http import JsonResponse
from django.views import View
from scriptly.models.core import Script

class ScriptlyScriptSearchJSON(View):
    def get(self, request):
        query = request.GET.get("q", "").strip()
        scripts = Script.objects.filter(script_name__icontains=query, is_active=True).select_related("script_group")
        results = []

        for script in scripts:
            try:
                url = script.latest_version.get_url()
                results.append({
                    "name": script.script_name,
                    "url": script.get_url(),
                })
            except Exception as e:
                # Optional: skip or log if a script doesn't have a group or version
                continue

        return JsonResponse({"results": results})

scriptly/templates/scriptly/base.html
{% load i18n %}
{% load static %}
<link rel="stylesheet" href="{% static 'scriptly/css/custom_dashboard.css' %}">
{% load scriptly_tags %}
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>{% block title %}{% get_scriptly_setting "SCRIPTLY_SITE_NAME" %}{% endblock title %}</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
        <link rel="stylesheet" href="//cdn.datatables.net/responsive/1.0.5/css/dataTables.responsive.css"/>
        <link rel="stylesheet" href="{% static "scriptly/css/base.css" %}"/>
        <link rel="stylesheet" href="{% static "scriptly/css/simple-sidebar.css" %}"/>
        <link href='//fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

        {% block extra_css %}
        {% endblock extra_css %}


        <style>
            {% block extra_style %}
            {% endblock extra_style %}
        </style>
    </head>
    <body class="{% if user.is_authenticated %}user-is-authenticated{% else %}user-is-anonymous{% endif %}">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button id="menu-toggle" class="navbar-toggle">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <ol class="breadcrumb navbar-breadcrumb">
                        <li><a href="{% url 'scriptly_home' %}" class="navbar-brand Scriptly">
                        {% get_scriptly_setting "SCRIPTLY_SITE_NAME" %}</a></li>
                        {% block breadcrumbs %}{% endblock %}
                    </ol>

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
                        <span class="sr-only">{% trans "Toggle navigation" %}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'scriptly:user_results' %}">{% trans "Results" %}</a>
                        </li>

                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'scriptly:profile_home' %}"><span class="glyphicon glyphicon-user"> </span> {{ request.user.username }}</a></li>
                            <li><a href="{% url 'admin:logout' %}?next={{ request.path }}">{% trans "Logout" %}</a></li>
                        {% else %}
                            <li>{% include "scriptly/registration/login_header.html" %}</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div id="wrapper">
            <div id="sidebar-wrapper" class="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li>
                        <form>
                            <div class="form-group">
                                <input type="text" class="form-control" id="sidebarsearchform"  placeholder="{% trans 'Search for scripts...' %}" value="{{ request.GET.q }}">
                            </div>
                        </form>
                    </li>
                    <div id="sidebarsearchresults">
                    </div>
                </ul>
            </div>

            <div id="page-content-wrapper" class="{% block page_content_class %}{% endblock page_content_class %}">
                {% block outer_content %}{% endblock %}
                {% block center %}
                    <div class="center-div {% block center_content_class %}col-md-10 col-xs-6{% endblock center_content_class %}">
                        {% block center_content %}
                        {% endblock center_content %}
                    </div>
                {% endblock center %}
            </div>
        </div>

        {% block js %}
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <script src="{% static 'scriptly/js/group_card_toggle.js' %}?v=2"></script>
            <script src="{% static 'scriptly/js/script_form.js' %}"></script>
        {% endblock js %}

        <div id="inline-js">
{% block inline_js %}
        <script>
            $(document).ready(function () {
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    $("#sidebarsearchform").on("keyup", function () {
        var query = $(this).val();
        if (query.length < 2) {
            $("#sidebarsearchresults").empty();
            return;
        }

        $.ajax({
            url: "{% url 'scriptly:scriptly_search_script_json' %}",
            method: "GET",
            data: { q: query },
            dataType: "json",
            success: function (data) {
                const $results = $("#sidebarsearchresults");
                $results.empty();

                if (data.results.length === 0) {
                    $results.append("<li><em>No results</em></li>");
                    return;
                }

                data.results.forEach(result => {
                    $results.append(`<li class="sidebarsearchresult"><a href="${result.url}">${result.name}</a></li>`);
                });

                $(".sidebarsearchresult a").on("click", function () {
                    $("#sidebarsearchresults").empty();
                });
            }
        });
    });
});

        </script>
<script>
$(document).on('submit', '.script-form', function(e) {
    e.preventDefault();

    const $form = $(this);
    const url = $form.attr('action');
    const formData = new FormData(this);

    $.ajax({
        type: "POST",
        url: url,
        data: formData,
        processData: false,
        contentType: false,
        success: function (response) {
            if (response.valid && response.redirect) {
                window.location.href = response.redirect;
            } else {
                alert("Validation failed");
                console.log(response.errors);
            }
        },
        error: function () {
            alert("Submission failed. Please try again.");
        }
    });
});
</script>

        {% endblock inline_js %}
        </div>

    </body>
</html>

scriptly/templates/scriptly/home.html
{% extends "scriptly/base.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'scriptly/css/custom_dashboard.css' %}">
  <link rel="stylesheet" href="{% static 'scriptly/css/script_form.css' %}">

{% endblock %}

{% block center_content %}
<div class="container content-section">
  <h1 class="script-groups-header">Available Groups</h1>
  <div class="row">
    {% for group in groups %}
      <div class="col-md-4 col-sm-6 mb-4">
        <div class="group-card theme-{% cycle '1' '2' '3' '4' '5' %}">
          <div class="group-card-header">
            <h3>{{ group.group_name }}</h3>
            {% if group.description %}
              <p class="group-description d-none d-expanded-block">{{ group.description }}</p>
            {% endif %}
          </div>

          <div class="group-card-body">
            <div class="bg-letter">{{ group.group_name|first|upper }}</div>
            {% if group.description %}
              <p class="description d-expanded-none">{{ group.description }}</p>
            {% endif %}

            <div class="group-scripts">
              {% if group.scripts %}
                <table class="script-table">
                  <thead>
                    <tr>
                      <th>Script Name</th>
                      <th>Description</th>
                      <th>Last Updated</th>
                      <th>Created By</th>

                    </tr>
                  </thead>
                  <tbody>
                    {% for script in group.scripts %}
                      <tr class="script-link" data-url="{% url 'scriptly:scriptly_script' slug=script.slug %}">
                        <td>{{ script.script_name }}</td>
                        <td>{{ script.script_description }}</td>
                        <td>
                          {% if script.modified_date %}
                            {{ script.modified_date|date:"M d, Y H:i" }}
                          {% else %}
                            Unknown
                          {% endif %}
                        </td>
                       <td>
                         {{ script.created_by }}
                       </td>




                      </tr>
                    {% endfor %}
                  </tbody>

                </table>
              {% else %}
                <p class="text-muted">No scripts in this group.</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block extra_js %}
  <script src="{% static 'scriptly/js/group_card_toggle.js' %}"></script>
  <script src="{% static 'scriptly/js/script_form.js' %}"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const hash = window.location.hash;
    if (hash && hash.startsWith("#script-")) {
      const scriptCard = document.querySelector(hash);
      if (scriptCard) {
        scriptCard.classList.add("expanded");
        scriptCard.scrollIntoView({ behavior: "smooth", block: "start" });
      }
    }
  });
</script>

{% endblock %}

scriptly/templates/scriptly/scrapbook.html
{% extends "Scriptly/base.html" %}
{% load i18n %}
{% load scriptly_tags %}

{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/3.3.0/ekko-lightbox.min.js"></script>
{% endblock extra_js %}
{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/3.3.0/ekko-lightbox.min.css"/>
{% endblock extra_css %}
{% block extra_style %}
    {{ block.super }}
    #Scriptly-task-submit {
    float: left;
    margin-left: 3px;
    }
{% endblock extra_style %}
{% block left_sidebar %}{% endblock left_sidebar %}
{% block center_content_class %}col-md-12 col-xs-12{% endblock center_content_class %}
{% block center_content %}

    <div class="row">
        {% with True as show_preview_metadata %}

            {% for output_group, output_files in file_groups.items %}
                {% for output_file_content in output_files %}
                    {% include 'Scriptly/preview/'|concat:output_group|concat:'.html' %}
                {% endfor %}
            {% endfor %}

        {% endwith %}

    </div>

{% endblock center_content %}

scriptly/templates/scriptly/script_group_detail.html
{% extends "Scriptly/base.html" %}
{% load static %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'Scriptly/css/group_detail.css' %}">
{% endblock %}

{% block center_content %}
<div class="container mt-4">
  <div class="expandable-card" onclick="toggleCard(this)">
    <div class="expandable-header">
      <h2>{{ group.group_name }}</h2>
    </div>
    <div class="expandable-body">
      <ul class="script-list">
        {% for script in scripts %}
            <li class="script-item" id="script-{{ script.id }}">
              <h4>{{ script.script_name }}</h4>
              <p>{{ script.script_description }}</p>
              <small>Last modified: {{ script.modified_date|date:"Y-m-d H:i" }}</small>
              <p>Created by: {{ script.created_by }}</p>

          <form method="POST" action="{% url 'scriptly:scriptly_submit_script' %}" class="scriptly-job-form" data-script-id="{{ script.id }}">
              <div id="form-status-{{ script.id }}"></div>
                {% csrf_token %}
                {% for parser, forms in script.parsers.items %}
                  {% for group in forms %}
                    <fieldset>
                      <legend>{{ group.group_name }}</legend>
                      {{ group.form }}
                    </fieldset>
                  {% endfor %}
                {% endfor %}
                <input type="hidden" name="scriptly_type" value="{{ script.scriptly_form.scriptly_type.value }}">
                {% if script.scriptly_form.scriptly_parser %}
                  <input type="hidden" name="scriptly_parser" value="{{ script.scriptly_form.scriptly_parser.value }}">
                {% endif %}
                   <button id="Scriptly-form-submit" type="submit" class="btn btn-primary">
              </form>
            </li>
{% endfor %}

      </ul>
    </div>
  </div>
</div>
{% endblock %}

scriptly/templates/scriptly/script_launcher.html
{% extends "scriptly/base.html" %}
{% load static %}
{% block title %}Run Script{% endblock %}

{% block center_content %}
<div class="container">
    <h2>Run: {{ script.script_name }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Run</button>
    </form>
</div>
{% endblock %}